# Задание 1
right_answers = (1, 2, 3, 2, 1, 2, 1, 3, 1, 2, 1, 2, 3, 3, 2, 1, 2, 1, 2, 1)
answers = []
answers1 = int(input("Введите свой ответ 1: "))
answers2 = int(input("Введите свой ответ 2: "))
answers3 = int(input("Введите свой ответ 3: "))
answers4 = int(input("Введите свой ответ 4: "))
answers5 = int(input("Введите свой ответ 5: "))
answers6 = int(input("Введите свой ответ 6: "))
answers7 = int(input("Введите свой ответ 7: "))
answers8 = int(input("Введите свой ответ 8: "))
answers9 = int(input("Введите свой ответ 9: "))
answers10 = int(input("Введите свой ответ 10: "))
answers11 = int(input("Введите свой ответ 11: "))
answers12 = int(input("Введите свой ответ 12: "))
answers13 = int(input("Введите свой ответ 13: "))
answers14 = int(input("Введите свой ответ 14: "))
answers15 = int(input("Введите свой ответ 15: "))
answers16 = int(input("Введите свой ответ 16: "))
answers17 = int(input("Введите свой ответ 17: "))
answers18 = int(input("Введите свой ответ 18: "))
answers19 = int(input("Введите свой ответ 19: "))
answers20 = int(input("Введите свой ответ 20: "))
answers.append(answers1)
answers.append(answers2)
answers.append(answers3)
answers.append(answers4)
answers.append(answers5)
answers.append(answers6)
answers.append(answers7)
answers.append(answers8)
answers.append(answers9)
answers.append(answers10)
answers.append(answers11)
answers.append(answers12)
answers.append(answers13)
answers.append(answers14)
answers.append(answers15)
answers.append(answers16)
answers.append(answers17)
answers.append(answers18)
answers.append(answers19)
answers.append(answers20)
if answers == list(right_answers):
    print("Экзамен сдан")
else:
    print("Экзамен провален")
